version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: persona-fi-postgres
    environment:
      POSTGRES_DB: persona_fi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: persona123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
